name: Update Standings

on:
  schedule:
    - cron: "0 6 * * *"   # Runs every day at 6 AM UTC (midnight MDT)
  workflow_dispatch:       # Allows manual trigger from GitHub UI

jobs:
  update-standings:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser

      - name: Install ChromeDriver
        run: |
          sudo apt-get install -y chromium-chromedriver
          sudo ln -s /usr/lib/chromium-browser/chromedriver /usr/bin

      - name: Run scraper
        env:
          PATH: /usr/lib/chromium-browser/:$PATH
        run: python scrape_standings.py

      - name: Commit and push if changed
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add standings.json
          git diff --quiet || git commit -m "Update standings.json [skip ci]"
          git push
